"""
Therapy Models
==============
Database models for therapy sessions and plans.
"""

from datetime import datetime
from webapp import db
import json


class TherapySession(db.Model):
    """
    Therapy session model for tracking Q&A interactions with the therapy agent.
    
    This stores the state of a therapy planning session, including:
    - Child profile reference
    - Category being assessed (gross motor, speech, etc.)
    - Current developmental age estimate
    - Questions asked and answers received
    - Session status
    """
    
    __tablename__ = 'therapy_sessions'
    
    # Primary key
    id = db.Column(db.Integer, primary_key=True)
    
    # Foreign keys
    child_id = db.Column(db.Integer, db.ForeignKey('child_profiles.id'), nullable=False)
    
    # Session info
    category = db.Column(db.String(100), nullable=False)  # e.g., 'gross_motor', 'speech'
    session_id = db.Column(db.String(100), unique=True, nullable=False, index=True)
    
    # Developmental assessment
    initial_delay_months = db.Column(db.Integer)  # Initial estimated delay
    current_dev_age_months = db.Column(db.Integer)  # Updated based on Q&A
    
    # Q&A tracking
    questions_asked = db.Column(db.Text)  # JSON array of questions
    answers_received = db.Column(db.Text)  # JSON object of {question_id: answer}
    current_question_index = db.Column(db.Integer, default=0)
    
    # Session state
    status = db.Column(db.String(50), default='active')  # 'active', 'completed', 'abandoned'
    
    # Metadata
    started_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    completed_at = db.Column(db.DateTime)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def __repr__(self):
        return f'<TherapySession {self.session_id}>'
    
    def get_questions(self):
        """Get questions as list."""
        if not self.questions_asked:
            return []
        return json.loads(self.questions_asked)
    
    def set_questions(self, questions):
        """Set questions from list."""
        self.questions_asked = json.dumps(questions)
    
    def get_answers(self):
        """Get answers as dictionary."""
        if not self.answers_received:
            return {}
        return json.loads(self.answers_received)
    
    def set_answers(self, answers):
        """Set answers from dictionary."""
        self.answers_received = json.dumps(answers)
    
    def add_answer(self, question_id, answer):
        """Add a single answer."""
        answers = self.get_answers()
        answers[str(question_id)] = answer
        self.set_answers(answers)
    
    def mark_completed(self):
        """Mark session as completed."""
        self.status = 'completed'
        self.completed_at = datetime.utcnow()
        db.session.commit()
    
    def to_dict(self):
        """Convert to dictionary."""
        return {
            'id': self.id,
            'child_id': self.child_id,
            'category': self.category,
            'session_id': self.session_id,
            'initial_delay_months': self.initial_delay_months,
            'current_dev_age_months': self.current_dev_age_months,
            'questions': self.get_questions(),
            'answers': self.get_answers(),
            'current_question_index': self.current_question_index,
            'status': self.status,
            'started_at': self.started_at.isoformat(),
            'completed_at': self.completed_at.isoformat() if self.completed_at else None,
            'updated_at': self.updated_at.isoformat()
        }


class TherapyPlan(db.Model):
    """
    Therapy plan model for storing generated activity plans.
    
    This stores the final therapy plan generated by the agent,
    including activities, milestones, and schedule.
    """
    
    __tablename__ = 'therapy_plans'
    
    # Primary key
    id = db.Column(db.Integer, primary_key=True)
    
    # Foreign keys
    child_id = db.Column(db.Integer, db.ForeignKey('child_profiles.id'), nullable=False)
    session_id = db.Column(db.Integer, db.ForeignKey('therapy_sessions.id'))
    
    # Plan info
    category = db.Column(db.String(100), nullable=False)
    title = db.Column(db.String(200))
    
    # Plan content
    developmental_age_months = db.Column(db.Integer)
    focus_milestones = db.Column(db.Text)  # JSON array of milestone objects
    activities = db.Column(db.Text)  # JSON array of activity objects
    schedule = db.Column(db.Text)  # JSON object with daily schedule
    
    # Additional info
    recommendations = db.Column(db.Text)
    safety_notes = db.Column(db.Text)
    
    # Status
    status = db.Column(db.String(50), default='active')  # 'active', 'completed', 'archived'
    
    # Metadata
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    start_date = db.Column(db.Date)
    end_date = db.Column(db.Date)
    
    def __repr__(self):
        return f'<TherapyPlan {self.id} - {self.category}>'
    
    def get_focus_milestones(self):
        """Get focus milestones as list."""
        if not self.focus_milestones:
            return []
        return json.loads(self.focus_milestones)
    
    def set_focus_milestones(self, milestones):
        """Set focus milestones from list."""
        self.focus_milestones = json.dumps(milestones)
    
    def get_activities(self):
        """Get activities as list."""
        if not self.activities:
            return []
        return json.loads(self.activities)
    
    def set_activities(self, activities):
        """Set activities from list."""
        self.activities = json.dumps(activities)
    
    def get_schedule(self):
        """Get schedule as dictionary."""
        if not self.schedule:
            return {}
        return json.loads(self.schedule)
    
    def set_schedule(self, schedule):
        """Set schedule from dictionary."""
        self.schedule = json.dumps(schedule)
    
    def to_dict(self):
        """Convert to dictionary."""
        return {
            'id': self.id,
            'child_id': self.child_id,
            'session_id': self.session_id,
            'category': self.category,
            'title': self.title,
            'developmental_age_months': self.developmental_age_months,
            'focus_milestones': self.get_focus_milestones(),
            'activities': self.get_activities(),
            'schedule': self.get_schedule(),
            'recommendations': self.recommendations,
            'safety_notes': self.safety_notes,
            'status': self.status,
            'created_at': self.created_at.isoformat(),
            'updated_at': self.updated_at.isoformat(),
            'start_date': self.start_date.isoformat() if self.start_date else None,
            'end_date': self.end_date.isoformat() if self.end_date else None
        }


class MilestoneTracking(db.Model):
    """
    Milestone tracking model for monitoring child's developmental progress.
    
    Tracks which CDC milestones have been achieved and when.
    """
    
    __tablename__ = 'milestone_tracking'
    
    # Primary key
    id = db.Column(db.Integer, primary_key=True)
    
    # Foreign keys
    child_id = db.Column(db.Integer, db.ForeignKey('child_profiles.id'), nullable=False)
    
    # Milestone info
    category = db.Column(db.String(100), nullable=False)
    milestone_text = db.Column(db.Text, nullable=False)
    milestone_age_months = db.Column(db.Integer)  # Expected age for milestone
    
    # Tracking
    achieved = db.Column(db.Boolean, default=False)
    achieved_at = db.Column(db.DateTime)
    child_age_at_achievement = db.Column(db.Integer)  # Age in months when achieved
    
    # Notes
    notes = db.Column(db.Text)
    
    # Metadata
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def __repr__(self):
        return f'<MilestoneTracking {self.id}>'
    
    def mark_achieved(self, child_age_months):
        """Mark milestone as achieved."""
        self.achieved = True
        self.achieved_at = datetime.utcnow()
        self.child_age_at_achievement = child_age_months
        db.session.commit()
    
    def to_dict(self):
        """Convert to dictionary."""
        return {
            'id': self.id,
            'child_id': self.child_id,
            'category': self.category,
            'milestone_text': self.milestone_text,
            'milestone_age_months': self.milestone_age_months,
            'achieved': self.achieved,
            'achieved_at': self.achieved_at.isoformat() if self.achieved_at else None,
            'child_age_at_achievement': self.child_age_at_achievement,
            'notes': self.notes,
            'created_at': self.created_at.isoformat(),
            'updated_at': self.updated_at.isoformat()
        }
